# (Transitive RL) TRL Commands

python main.py --env_name=scene-play-oraclerep-v0 --agent=agents/trl.py --offline_steps=1000000 --agent.actor_hidden_dims="(512, 512, 512)" --agent.value_hidden_dims="(512, 512, 512)" --agent.dataset.actor_geom_sample=False --agent.dataset.actor_p_trajgoal=1.0 --agent.dataset.actor_p_randomgoal=0.0 --agent.dataset.value_geom_sample=True --agent.discount=0.99 --agent.oracle_distill=True --agent.expectile=0.7 --agent.lam=1.0 --agent.pe_type=rpg --agent.rpg.alpha=1

python main.py --env_name=cube-single-play-oraclerep-v0 --agent=agents/trl.py --offline_steps=1000000 --agent.actor_hidden_dims="(512, 512, 512)" --agent.value_hidden_dims="(512, 512, 512)" --agent.dataset.actor_geom_sample=False --agent.dataset.actor_p_trajgoal=1.0 --agent.dataset.actor_p_randomgoal=0.0 --agent.dataset.value_geom_sample=True --agent.discount=0.99 --agent.oracle_distill=True --agent.expectile=0.7 --agent.lam=0.7 --agent.pe_type=rpg --agent.rpg.alpha=1

python main.py --env_name=cube-double-play-oraclerep-v0 --agent=agents/trl.py --offline_steps=1000000 --agent.actor_hidden_dims="(512, 512, 512)" --agent.value_hidden_dims="(512, 512, 512)" --agent.dataset.actor_geom_sample=False --agent.dataset.actor_p_trajgoal=1.0 --agent.dataset.actor_p_randomgoal=0.0 --agent.dataset.value_geom_sample=True --agent.discount=0.99 --agent.oracle_distill=True --agent.expectile=0.7 --agent.lam=1 --agent.pe_type=rpg --agent.rpg.alpha=10

python main.py --env_name=puzzle-3x3-play-oraclerep-v0 --agent=agents/trl.py --offline_steps=1000000 --agent.actor_hidden_dims="(512, 512, 512)" --agent.value_hidden_dims="(512, 512, 512)" --agent.dataset.actor_geom_sample=False --agent.dataset.actor_p_trajgoal=1.0 --agent.dataset.actor_p_randomgoal=0.0 --agent.dataset.value_geom_sample=True --agent.discount=0.99 --agent.oracle_distill=True --agent.expectile=0.7 --agent.lam=0.5 --agent.pe_type=rpg --agent.rpg.alpha=2

python main.py --env_name=puzzle-4x4-play-oraclerep-v0 --agent=agents/trl.py --offline_steps=1000000 --agent.actor_hidden_dims="(512, 512, 512)" --agent.value_hidden_dims="(512, 512, 512)" --agent.dataset.actor_geom_sample=False --agent.dataset.actor_p_trajgoal=1.0 --agent.dataset.actor_p_randomgoal=0.0 --agent.dataset.value_geom_sample=True --agent.discount=0.99 --agent.oracle_distill=True --agent.expectile=0.7 --agent.lam=2.0 --agent.pe_type=rpg --agent.rpg.alpha=2

python main.py --env_name=antmaze-large-navigate-oraclerep-v0 --agent=agents/trl.py --offline_steps=1000000 --agent.actor_hidden_dims="(512, 512, 512)" --agent.value_hidden_dims="(512, 512, 512)" --agent.dataset.actor_geom_sample=False --agent.dataset.actor_p_trajgoal=1.0 --agent.dataset.actor_p_randomgoal=0.0 --agent.dataset.value_geom_sample=True --agent.discount=0.99 --agent.oracle_distill=True --agent.expectile=0.7 --agent.lam=0.0 --agent.pe_type=rpg --agent.rpg.alpha=0.7

python main.py --env_name=antsoccer-arena-navigate-oraclerep-v0 --agent=agents/trl.py --offline_steps=1000000 --agent.actor_hidden_dims="(512, 512, 512)" --agent.value_hidden_dims="(512, 512, 512)" --agent.dataset.actor_geom_sample=False --agent.dataset.actor_p_trajgoal=1.0 --agent.dataset.actor_p_randomgoal=0.0 --agent.dataset.value_geom_sample=True --agent.discount=0.99 --agent.oracle_distill=True --agent.expectile=0.7 --agent.lam=0.5 --agent.pe_type=rpg --agent.rpg.alpha=0.3

python main.py --env_name=humanoidmaze-medium-navigate-oraclerep-v0 --agent=agents/trl.py --offline_steps=1000000 --agent.actor_hidden_dims="(512, 512, 512)" --agent.value_hidden_dims="(512, 512, 512)" --agent.dataset.actor_geom_sample=False --agent.dataset.actor_p_trajgoal=1.0 --agent.dataset.actor_p_randomgoal=0.0 --agent.dataset.value_geom_sample=True --agent.discount=0.995 --agent.oracle_distill=True --agent.expectile=0.7 --agent.lam=0.0 --agent.pe_type=rpg --agent.rpg.alpha=0.1

python main.py --env_name=humanoidmaze-large-navigate-oraclerep-v0 --agent=agents/trl.py --offline_steps=1000000 --agent.actor_hidden_dims="(512, 512, 512)" --agent.value_hidden_dims="(512, 512, 512)" --agent.dataset.actor_geom_sample=False --agent.dataset.actor_p_trajgoal=1.0 --agent.dataset.actor_p_randomgoal=0.0 --agent.dataset.value_geom_sample=True --agent.discount=0.995 --agent.oracle_distill=True --agent.expectile=0.7 --agent.lam=0.1 --agent.pe_type=rpg --agent.rpg.alpha=0.1

python main.py --env_name=pointmaze-medium-navigate-oraclerep-v0 --agent=agents/trl.py --offline_steps=1000000 --agent.actor_hidden_dims="(512, 512, 512)" --agent.value_hidden_dims="(512, 512, 512)" --agent.dataset.actor_geom_sample=False --agent.dataset.actor_p_trajgoal=1.0 --agent.dataset.actor_p_randomgoal=0.0 --agent.dataset.value_geom_sample=True --agent.discount=0.99 --agent.oracle_distill=True --agent.expectile=0.7 --agent.lam=0.7 --agent.pe_type=rpg --agent.rpg.alpha=10

python main.py --env_name=puzzle-4x5-play-oraclerep-v0 --dataset_dir=<insert_dir> --agent=agents/trl.py --offline_steps=1000000 --agent.actor_hidden_dims="(1024, 1024, 1024, 1024)" --agent.value_hidden_dims="(1024, 1024, 1024, 1024)" --agent.discount=0.999 --dataset_replace_interval=1000 --agent.actor_geom_sample=True --agent.actor_p_trajgoal=0.5 --agent.actor_p_randomgoal=0.5 --agent.value_geom_sample=False --agent.value_p_trajgoal=1.0 --agent.value_p_randomgoal=0.0 --agent.oracle_distill=True --agent.expectile=0.7 --agent.lam=0 --agent.pe_type=frs

python main.py --env_name=puzzle-4x6-play-oraclerep-v0 --dataset_dir=<insert_dir> --agent=agents/trl.py --offline_steps=1000000 --agent.actor_hidden_dims="(1024, 1024, 1024, 1024)" --agent.value_hidden_dims="(1024, 1024, 1024, 1024)" --agent.discount=0.999 --dataset_replace_interval=1000 --agent.actor_geom_sample=True --agent.actor_p_trajgoal=0.5 --agent.actor_p_randomgoal=0.5 --agent.value_geom_sample=False --agent.value_p_trajgoal=1.0 --agent.value_p_randomgoal=0.0 --agent.oracle_distill=True --agent.expectile=0.7 --agent.lam=0 --agent.pe_type=frs

python main.py --env_name=humanoidmaze-giant-navigate-oraclerep-v0 --dataset_dir=<insert_dir> --agent=agents/trl.py --offline_steps=1000000 --agent.actor_hidden_dims="(1024, 1024, 1024, 1024)" --agent.value_hidden_dims="(1024, 1024, 1024, 1024)" --agent.discount=0.999 --dataset_replace_interval=4000 --agent.actor_geom_sample=False --agent.actor_p_trajgoal=1.0 --agent.actor_p_randomgoal=0.0 --agent.value_geom_sample=False --agent.value_p_trajgoal=1.0 --agent.value_p_randomgoal=0.0 --agent.oracle_distill=True --agent.expectile=0.7 --agent.lam=0 --agent.pe_type=rpg --agent.rpg.alpha=0.1

# ATRL Commands
# Deterministic tasks

python main.py --env_name=scene-play-oraclerep-v0 --agent=agents/atrl.py --offline_steps=1000000 --agent.actor_hidden_dims="(512, 512, 512)" --agent.value_hidden_dims="(512, 512, 512)" --agent.dataset.actor_geom_sample=False --agent.dataset.actor_p_trajgoal=1.0 --agent.dataset.actor_p_randomgoal=0.0 --agent.dataset.value_geom_sample=True --agent.dataset.value_p_trajgoal=0.7 --agent.dataset.value_p_randomgoal=0.3 --agent.discount=0.99 --agent.oracle_distill=True --agent.expectile=0.7 --agent.td_expectile=0.5 --agent.use_anchored_target=True --agent.use_hindsight_weight=True --agent.hindsight_weight_clip=1.0 --agent.lam=0.7 --agent.pe_type=rpg --agent.rpg.alpha=1.5

python main.py --env_name=cube-single-play-oraclerep-v0 --agent=agents/atrl.py --offline_steps=1000000 --agent.actor_hidden_dims="(512, 512, 512)" --agent.value_hidden_dims="(512, 512, 512)" --agent.dataset.actor_geom_sample=False --agent.dataset.actor_p_trajgoal=1.0 --agent.dataset.actor_p_randomgoal=0.0 --agent.dataset.value_geom_sample=True --agent.dataset.value_p_trajgoal=0.7 --agent.dataset.value_p_randomgoal=0.3 --agent.discount=0.99 --agent.oracle_distill=True --agent.expectile=0.7 --agent.td_expectile=0.5 --agent.use_anchored_target=True --agent.use_hindsight_weight=True --agent.hindsight_weight_clip=1.0 --agent.lam=0.4 --agent.pe_type=rpg --agent.rpg.alpha=2.5

python main.py --env_name=cube-double-play-oraclerep-v0 --agent=agents/atrl.py --offline_steps=1000000 --agent.actor_hidden_dims="(512, 512, 512)" --agent.value_hidden_dims="(512, 512, 512)" --agent.dataset.actor_geom_sample=False --agent.dataset.actor_p_trajgoal=1.0 --agent.dataset.actor_p_randomgoal=0.0 --agent.dataset.value_geom_sample=True --agent.dataset.value_p_trajgoal=0.7 --agent.dataset.value_p_randomgoal=0.3 --agent.discount=0.99 --agent.oracle_distill=True --agent.expectile=0.7 --agent.td_expectile=0.5 --agent.use_anchored_target=True --agent.use_hindsight_weight=True --agent.hindsight_weight_clip=1.0 --agent.lam=0.0 --agent.pe_type=rpg --agent.rpg.alpha=7.5

python main.py --env_name=puzzle-3x3-play-oraclerep-v0 --agent=agents/atrl.py --offline_steps=1000000 --agent.actor_hidden_dims="(512, 512, 512)" --agent.value_hidden_dims="(512, 512, 512)" --agent.dataset.actor_geom_sample=False --agent.dataset.actor_p_trajgoal=1.0 --agent.dataset.actor_p_randomgoal=0.0 --agent.dataset.value_geom_sample=True --agent.dataset.value_p_trajgoal=0.7 --agent.dataset.value_p_randomgoal=0.3 --agent.discount=0.99 --agent.oracle_distill=True --agent.expectile=0.7 --agent.td_expectile=0.5 --agent.use_anchored_target=True --agent.use_hindsight_weight=True --agent.hindsight_weight_clip=1.0 --agent.lam=0.4 --agent.pe_type=rpg --agent.rpg.alpha=1.5

python main.py --env_name=puzzle-4x4-play-oraclerep-v0 --agent=agents/atrl.py --offline_steps=1000000 --agent.actor_hidden_dims="(512, 512, 512)" --agent.value_hidden_dims="(512, 512, 512)" --agent.dataset.actor_geom_sample=False --agent.dataset.actor_p_trajgoal=1.0 --agent.dataset.actor_p_randomgoal=0.0 --agent.dataset.value_geom_sample=True --agent.dataset.value_p_trajgoal=0.7 --agent.dataset.value_p_randomgoal=0.3 --agent.discount=0.99 --agent.oracle_distill=True --agent.expectile=0.7 --agent.td_expectile=0.5 --agent.use_anchored_target=True --agent.use_hindsight_weight=True --agent.hindsight_weight_clip=1.0 --agent.lam=0.1 --agent.pe_type=rpg --agent.rpg.alpha=1.0

python main.py --env_name=antmaze-large-navigate-oraclerep-v0 --agent=agents/atrl.py --offline_steps=1000000 --agent.actor_hidden_dims="(512, 512, 512)" --agent.value_hidden_dims="(512, 512, 512)" --agent.dataset.actor_geom_sample=False --agent.dataset.actor_p_trajgoal=1.0 --agent.dataset.actor_p_randomgoal=0.0 --agent.dataset.value_geom_sample=True --agent.dataset.value_p_trajgoal=0.7 --agent.dataset.value_p_randomgoal=0.3 --agent.discount=0.99 --agent.oracle_distill=True --agent.expectile=0.7 --agent.td_expectile=0.5 --agent.use_anchored_target=True --agent.use_hindsight_weight=True --agent.hindsight_weight_clip=1.0 --agent.lam=0.0 --agent.pe_type=rpg --agent.rpg.alpha=0.25

python main.py --env_name=antsoccer-arena-navigate-oraclerep-v0 --agent=agents/atrl.py --offline_steps=1000000 --agent.actor_hidden_dims="(512, 512, 512)" --agent.value_hidden_dims="(512, 512, 512)" --agent.dataset.actor_geom_sample=False --agent.dataset.actor_p_trajgoal=1.0 --agent.dataset.actor_p_randomgoal=0.0 --agent.dataset.value_geom_sample=True --agent.dataset.value_p_trajgoal=0.7 --agent.dataset.value_p_randomgoal=0.3 --agent.discount=0.99 --agent.oracle_distill=True --agent.expectile=0.7 --agent.td_expectile=0.5 --agent.use_anchored_target=True --agent.use_hindsight_weight=True --agent.hindsight_weight_clip=1.0 --agent.lam=0.5 --agent.pe_type=rpg --agent.rpg.alpha=0.25

python main.py --env_name=humanoidmaze-medium-navigate-oraclerep-v0 --agent=agents/atrl.py --offline_steps=1000000 --agent.actor_hidden_dims="(512, 512, 512)" --agent.value_hidden_dims="(512, 512, 512)" --agent.dataset.actor_geom_sample=False --agent.dataset.actor_p_trajgoal=1.0 --agent.dataset.actor_p_randomgoal=0.0 --agent.dataset.value_geom_sample=True --agent.dataset.value_p_trajgoal=0.7 --agent.dataset.value_p_randomgoal=0.3 --agent.discount=0.995 --agent.oracle_distill=True --agent.expectile=0.7 --agent.td_expectile=0.5 --agent.use_anchored_target=True --agent.use_hindsight_weight=True --agent.hindsight_weight_clip=1.0 --agent.lam=0.0 --agent.pe_type=rpg --agent.rpg.alpha=0.1

python main.py --env_name=humanoidmaze-large-navigate-oraclerep-v0 --agent=agents/atrl.py --offline_steps=1000000 --agent.actor_hidden_dims="(512, 512, 512)" --agent.value_hidden_dims="(512, 512, 512)" --agent.dataset.actor_geom_sample=False --agent.dataset.actor_p_trajgoal=1.0 --agent.dataset.actor_p_randomgoal=0.0 --agent.dataset.value_geom_sample=True --agent.dataset.value_p_trajgoal=0.7 --agent.dataset.value_p_randomgoal=0.3 --agent.discount=0.995 --agent.oracle_distill=True --agent.expectile=0.7 --agent.td_expectile=0.5 --agent.use_anchored_target=True --agent.use_hindsight_weight=True --agent.hindsight_weight_clip=1.0 --agent.lam=0.0 --agent.pe_type=rpg --agent.rpg.alpha=0.1

python main.py --env_name=pointmaze-large-navigate-oraclerep-v0 --agent=agents/atrl.py --offline_steps=1000000 --agent.actor_hidden_dims="(512, 512, 512)" --agent.value_hidden_dims="(512, 512, 512)" --agent.dataset.actor_geom_sample=False --agent.dataset.actor_p_trajgoal=1.0 --agent.dataset.actor_p_randomgoal=0.0 --agent.dataset.value_geom_sample=True --agent.dataset.value_p_trajgoal=0.7 --agent.dataset.value_p_randomgoal=0.3 --agent.discount=0.99 --agent.oracle_distill=True --agent.expectile=0.7 --agent.td_expectile=0.5 --agent.use_anchored_target=True --agent.use_hindsight_weight=True --agent.hindsight_weight_clip=1.0 --agent.lam=0.1 --agent.pe_type=rpg --agent.rpg.alpha=0.1

# Stochastic tasks

python main.py --env_name=pointmaze-teleport-navigate-oraclerep-v0 --agent=agents/atrl.py --offline_steps=1000000 --agent.actor_hidden_dims="(512, 512, 512)" --agent.value_hidden_dims="(512, 512, 512)" --agent.dataset.actor_geom_sample=False --agent.dataset.actor_p_trajgoal=1.0 --agent.dataset.actor_p_randomgoal=0.0 --agent.dataset.value_geom_sample=True --agent.dataset.value_p_trajgoal=0.7 --agent.dataset.value_p_randomgoal=0.3 --agent.discount=0.99 --agent.oracle_distill=True --agent.expectile=0.7 --agent.td_expectile=0.5 --agent.use_anchored_target=True --agent.use_hindsight_weight=True --agent.hindsight_weight_clip=1.0 --agent.lam=0.1 --agent.pe_type=rpg --agent.rpg.alpha=0.1

python main.py --env_name=pointmaze-teleport-stitch-oraclerep-v0 --agent=agents/atrl.py --offline_steps=1000000 --agent.actor_hidden_dims="(512, 512, 512)" --agent.value_hidden_dims="(512, 512, 512)" --agent.dataset.actor_geom_sample=False --agent.dataset.actor_p_trajgoal=1.0 --agent.dataset.actor_p_randomgoal=0.0 --agent.dataset.value_geom_sample=True --agent.dataset.value_p_trajgoal=0.7 --agent.dataset.value_p_randomgoal=0.3 --agent.discount=0.99 --agent.oracle_distill=True --agent.expectile=0.7 --agent.td_expectile=0.5 --agent.use_anchored_target=True --agent.use_hindsight_weight=True --agent.hindsight_weight_clip=1.0 --agent.lam=0.7 --agent.pe_type=rpg --agent.rpg.alpha=10.0

python main.py --env_name=antmaze-teleport-navigate-oraclerep-v0 --agent=agents/atrl.py --offline_steps=1000000 --agent.actor_hidden_dims="(512, 512, 512)" --agent.value_hidden_dims="(512, 512, 512)" --agent.dataset.actor_geom_sample=False --agent.dataset.actor_p_trajgoal=1.0 --agent.dataset.actor_p_randomgoal=0.0 --agent.dataset.value_geom_sample=True --agent.dataset.value_p_trajgoal=0.7 --agent.dataset.value_p_randomgoal=0.3 --agent.discount=0.99 --agent.oracle_distill=True --agent.expectile=0.7 --agent.td_expectile=0.5 --agent.use_anchored_target=True --agent.use_hindsight_weight=True --agent.hindsight_weight_clip=1.0 --agent.lam=0.0 --agent.pe_type=rpg --agent.rpg.alpha=0.25

python main.py --env_name=antmaze-teleport-stitch-oraclerep-v0 --agent=agents/atrl.py --offline_steps=1000000 --agent.actor_hidden_dims="(512, 512, 512)" --agent.value_hidden_dims="(512, 512, 512)" --agent.dataset.actor_geom_sample=False --agent.dataset.actor_p_trajgoal=1.0 --agent.dataset.actor_p_randomgoal=0.0 --agent.dataset.value_geom_sample=True --agent.dataset.value_p_trajgoal=0.7 --agent.dataset.value_p_randomgoal=0.3 --agent.discount=0.99 --agent.oracle_distill=True --agent.expectile=0.7 --agent.td_expectile=0.5 --agent.use_anchored_target=True --agent.use_hindsight_weight=True --agent.hindsight_weight_clip=1.0 --agent.lam=0.0 --agent.pe_type=rpg --agent.rpg.alpha=0.25

python main.py --env_name=antmaze-teleport-explore-oraclerep-v0 --agent=agents/atrl.py --offline_steps=1000000 --agent.actor_hidden_dims="(512, 512, 512)" --agent.value_hidden_dims="(512, 512, 512)" --agent.dataset.actor_geom_sample=False --agent.dataset.actor_p_trajgoal=0.0 --agent.dataset.actor_p_randomgoal=1.0 --agent.dataset.value_geom_sample=True --agent.dataset.value_p_trajgoal=0.7 --agent.dataset.value_p_randomgoal=0.3 --agent.discount=0.99 --agent.oracle_distill=True --agent.expectile=0.7 --agent.td_expectile=0.5 --agent.use_anchored_target=True --agent.use_hindsight_weight=True --agent.hindsight_weight_clip=1.0 --agent.lam=0.0 --agent.pe_type=rpg --agent.rpg.alpha=0.25
